langchain4j:
  open-ai:
    chat-model:
      #      api-key: ${OPENAI_API_KEY}
      api-key: demo
      #    streaming-chat-model:
      #      api-key: ${OPENAI_API_KEY}

      # 默认（可选地）
      model-name: gpt-3.5-turbo
      temperature: 0.7
#      log-requests: true
#      log-responses: true

# 日志输出（可选地）
logging:
  level:
    dev:
      langchain4j: DEBUG
    ai4j:
      openai4j: DEBUG