server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 2049MB     # 设置单文件大小 2G
      max-request-size: 5121MB  # 设置总上传数据总大小 5G

  datasource:
    url: jdbc:h2:./test   # 自定生成的数据库存储位置：当前项目根目录./test、当前磁盘根目录/test、当前系统盘用户目录下~/test
    #    url: jdbc:h2:file:D:/database/h2/data/db/test   # 数据库持久化配置
    username: test
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true # 默认 false
  h2:
    console:
      enabled: true       # 默 false
      path: /h2-console   # http://localhost:8080/h2-console
      settings:
        web-allow-others: false
        trace: false
