server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 2049MB     # 设置单文件大小 2G
      max-request-size: 5121MB  # 设置总上传数据总大小 5G

deepseek:
  api_key: sk-62aa54bcf5b2478e88c4bcd4c6d855w2
  api_url: https://api.deepseek.com/v1
